version: 2
jobs:
  build:
    working_directory: ~/healthtrack
    docker:
      - image: circleci/ruby:2.5.1
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: healthtrack
          POSTGRES_DB: healthtrack-test
    steps:
      - checkout

      - restore_cache:
          keys:
            - healthtrack-{{ checksum "Gemfile.lock" }}
            - healthtrack-

      - run:
          name: Install dependencies
          command: |
            bundle install --path=vendor/bundle --jobs 4 --retry 3
      - run: sudo apt install -y postgresql-client || true

      - save_cache:
          key: healthtrack-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load

      - run:
          name: Run unit tests
          command: |
            bundle exec rspec