default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DB_DATABASE") { "db" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "localhost" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default